version: "3.9"

services:
  app:
    build: .
    container_name: spring_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - spring-network

  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: FAS
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: FAS@123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spring-network

volumes:
  postgres_data:

networks:
  spring-network: